### ISSUE TITLE
Wheel not pre-built for manylinux1 (AWS Lambda)

### ISSUE THREAD

**Issue by davnn** [kno10/python-kmedoids#13]
Interestingly, using the newly release version `0.3.2`, the install fails on the default Linux Github Actions runnerm, because it attempts a source install (no appropriate wheel found?).

```
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      Checking for Rust toolchain....
      [end of output]
```

Cannot locally reproduce on Linux or Windows. Might find time to further track down the issue, but maybe you have an idea?

**Comment by kno10** [comment]
Which pip version is installed? Does updating pip first help - I have seen pip update calls in many github actions scripts.
Maybe the binary pip tags were only added in pip >= 20.3 with [PEP 600](https://peps.python.org/pep-0600/) support.
I don't think we should be adding pip >= 20.3 to requirements, hence all we then possibly can do is to document this in the instructions. (Supposedly is fine on ALT Linux 10+, RHEL 9+, Debian 11+, Fedora 34+, Mageia 8+, Ubuntu 21.04+ then; but then possibly not yet on Ubuntu 20.04.4 LTS - we could then try to also build manylinux2014 tags)

**Comment by davnn** [comment]
I just found out that it's not the fault of github runner, but there appears to be no suitable release for the [AWS Lambda docker image](https://gallery.ecr.aws/lambda/python) for `0.3.2`, but for `0.3.1` there is. The following docker container fails to build:

```docker
FROM public.ecr.aws/lambda/python:3.9
RUN pip3 install --upgrade pip
RUN pip3 install kmedoids==0.3.2
```

Next example builds just fine.

```docker
FROM public.ecr.aws/lambda/python:3.9
RUN pip3 install --upgrade pip
RUN pip3 install kmedoids==0.3.1
```

I couldn't find out yet what the AWS Lambda docker image is based on, unfortunately.

**Comment by davnn** [comment]
So the question is how to release `manylinux1`, `manylinux2010`, `manylinux2014` and `manylinux_x_y` packages simultaneously.

The [maturin docs](https://github.com/PyO3/maturin#manylinux-and-auditwheel) mention that *If you want to publish widely usable wheels for linux pypi, you need to use a manylinux docker image.* As a real-world example maturin refers to the [fast-ctc-decode](https://github.com/nanoporetech/fast-ctc-decode/blob/b226ea0f2b2f4f474eff47349703d57d2ea4801b/.github/workflows/publish.yml) package. Their build workflow looks really clean, and, looking at the [built wheels](https://pypi.org/project/fast-ctc-decode/0.3.2/#files), they seem to be able to support all manylinux variants.

We should probably align our Github action with the one fast-ctc-decode uses.

**Comment by kno10** [comment]
I tried building on the manylinux1 containers, but that just causes dependency hell, as various github actions no longer work on such old OS.

**Comment by davnn** [comment]
It appears that scikit-learn dropped manylinux2010 support with `1.1.0` and numpy dropped manylinux2010 support with `1.22.0`. I would propose to align with the numpy manylinux support for future releases, i.e. we should try to provide manylinux2014 and manylinux2 support for now. I will shortly submit a pull request to add support.

**Comment by kno10** [comment]
Pull request looks good. Do these packages install on AWS Lamda images?

**Comment by davnn** [comment]
Yes, it's not really documented, but apparently they support 2014+.
