### ISSUE TITLE
failing to cluster block matrix correctly

### ISSUE THREAD

**Issue by hpelin** [kno10/python-kmedoids#20]
Hi, we wanted to use your package as a fast alternative to sklearn kmedoids and the unit test we implemented for our code failed. As you see, we created a block distance matrix with very clear 3 clusters. The following problems arose:
- With init method = 'build' the sklearn implementation gave us 3 labels and correct clusters, whereas kmedoids failed - it gave us 2 clusters even though we specifically asked for 3. 
- With init method = 'random' kmedoids did give us 3 clusters as we asked, but they are not really correct.

We don't see what might be leading to that, it would be great to know what is going on or fix it! Thanks!

``` 
import numpy as np
import kmedoids
from sklearn_extra.cluster import KMedoids

method_clustering = 'pam'
init_clustering = 'random'
max_iter_clustering = 100
n_clusters = 3
random_state = 42

distance_matrix = np.kron(np.eye(3,dtype=int),np.ones([10,10]))

cluster_method_orig = lambda X: KMedoids(n_clusters=n_clusters, random_state=random_state, init=init_clustering, method=method_clustering, max_iter=max_iter_clustering).fit(X).labels_
cluster_method_fast = lambda X: kmedoids.KMedoids(n_clusters=n_clusters, random_state=random_state, init=init_clustering, method=method_clustering, max_iter=max_iter_clustering).fit(X).labels_
labels_orig = cluster_method_orig(distance_matrix)
labels_fast = cluster_method_fast(distance_matrix)
print(f"Labels sklearn:  {labels_orig}")
print(f"Labels kmedoids: {labels_fast}")
```
Output for init_clustering = random:
Labels sklearn:  [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
Labels kmedoids: [0 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 1 1 1 0 1 1 1 1 1 1]

Output for init_clustering = build:
Labels sklearn:  [0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1]
Labels kmedoids: [0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]

**Comment by kno10** [comment]
Your input is *not* a proper distance matrix. Instead, it is a *similarity* matrix.

This is probably what you meant to use:
```
> distance_matrix = 1 - np.kron(np.eye(3,dtype=int),np.ones([10,10]))
> print(kmedoids.fasterpam(distance_matrix, 3).labels)
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
```

Also note that you did not pass `metric="precomputed"` to the sklearn_extra class. It defaults to computing euclidean distances of the rows of your block matrix, interpreting it as a 30-dimensional data matrix in euclidean vector space. So because you used that class the wrong way it appeared to work.

**Comment by hpelin** [comment]
Yes, it definitely did, we did not realise that the default metric is different between the methods. Thanks a lot, now we fixed our code :)
