### ISSUE TITLE
Add `OSX-ARM64` Variant in `conda-forge`

### ISSUE THREAD

**Issue by RoyiAvital** [kno10/python-kmedoids#25]
Currently there is no support for `kmedoids` in `conda-forge` for Apple Silicon. 

Could it be added?

**Comment by kno10** [comment]
Conda platform support is controlled by the anaconda infrastructure for all I can tell.

Conda issues need to be handled in the conda recpies, i.e., https://github.com/conda-forge/kmedoids-feedstock/issues

**Comment by kno10** [comment]
https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds
Has some details on osx-amd64 support in conda.
It appears you need to make a pull request in https://github.com/conda-forge/conda-forge-pinning-feedstock/ so they build the package for Apple Silicon.
The kmedoids itself does not have many dependencies and builds successfully on github for Apple Silicon via cross-compilation, so I do not expect many issues.

**Comment by kno10** [comment]
May be building already without the pinning. For progress, see conda-forge/kmedoids-feedstock/pull/5

**Comment by RoyiAvital** [comment]
@kno10 , Thanks for the effort.
It seems to fail for some reason on the link.

**Comment by kno10** [comment]
The build issues with OSX cross-compilation are resolved, there are osx-arm64 packages now on
https://anaconda.org/conda-forge/kmedoids

**Comment by RoyiAvital** [comment]
@kno10 , This is perfect!
Than you very much!
