### ISSUE TITLE
Question regarding visualizing medoid

### ISSUE THREAD

**Issue by khieu** [kno10/python-kmedoids#28]
I am using `python-kmedoids` package to compute clusters based on distance matrix and want to visualize the clusters. From my understanding, the input to `kmedoids` is a distance matrix and not coordinated points. My question is can I visualize the clusters (based on the centroid or something else)? The documentation indicated that `cluster_center` is `None` for `precomputed`. Do you have any suggestion on visualizing the result/output of this library?

thank you so much!

**Comment by kno10** [comment]
Medoids are data points; visualize them the same way as your data.
