### ISSUE TITLE
Question about labels consistency

### ISSUE THREAD

**Issue by khieu** [kno10/python-kmedoids#29]
I have a question wrt the label values consistencies of the output: Say we partition `MNIST` into `n ` equal subset (`n = 3` for example) where each subset contains all the digits. 
Assuming that `kmedoids` give the best partitioning possible (10 cluster where each cluster contains images of 1 digit), if I use `kmedoids` to partition each subset of `MNIST` separately, is there any guaranty that the `labels` or `labels_` outputs of the `kmedoids` algorithm to be stable/consistent in terms of label value? More specifically, is there a way to make sure that images of `0` acrossed all `MNIST` subsets will be labeled the same as some specific value `i`. Or is it the case that the information we got out of `kmedoids` is there are `k` different clusters and the labels only differentiate between the clusters, not provide any other meaning of the cluster?

Thank you so much for any help!

**Comment by kno10** [comment]
Clustering is unsupervised. The cluster numbers are integers 0 to (k-1), and do *not* have a particular meaning.
In particular, they will not align with some class labels that are *not* part of the input.

MNIST is a very poor example because it has labels 0 to 9 (and these do not correspond to clusters well, either). But obviously, a clustering algorithm cannot know this, nor align with the *human* interpretation of these classes.

**Comment by khieu** [comment]
Thanks for the explanation. I understand that the cluster label does not imply any meaning. My question here is simply to confirm that the class label are `not` consistent even with datasets that are known to be in the same distribution. A different example would be say we have an `alphabet` dataset that is partitioned with `k-fold`, then for each fold, assuming the ideal case, the letter `a` might be clustered together but will not shared the same label (say '5' for example).

Thanks!

**Comment by kno10** [comment]
Even with multiple random restarts, and even when it finds the exact same partitioning, the cluster labels may not be "consistent".
So if you have a dataset consisting of 1-dimensional points 1,2,3,100,101,102 you are expected to see the labels 0,0,0,1,1,1 and 1,1,1,0,0,0 equally often; they are equally good solutions to the optimization.
