### ISSUE TITLE
Numpy 2.0 support

### ISSUE THREAD

**Issue by apcamargo** [kno10/python-kmedoids#30]
[0.22.0](https://github.com/PyO3/rust-numpy/releases/tag/v0.22.0) introduced support for `numpy >= 2` in version 0.22.0. Would be good to have a new release with the updated dependency.

**Comment by apcamargo** [comment]
I wanted to have the conda-forge build work with `numpy >= 2` for a project that depends on Conda. But since you're waiting for another fix, I there's no reason to rush that :)

**Comment by kno10** [comment]
Version 0.5.3 builds with numpy 2 and python 3.13 (but likely not 3.13t yet), and is available on conda already.
Still struggling with automated pypi.org builds though - maturin produces too new metadata (Version 2.4) and the pypi upload seems to work only up to 2.3: https://github.com/pypa/gh-action-pypi-publish/issues/308
Trying a downgraded maturin for now to produce packages with metadata version 2.3 now
