### ISSUE TITLE
Import warnings in kmedoids/__init__.py

### ISSUE THREAD

**Issue by rjustindavis** [kno10/python-kmedoids#8]
Observe the following block, line 81-85 in kmedoids/__init__.py:

```python
import numpy as np, numbers
	if isinstance(medoids, np.ndarray):
		if random_state is not None:
			warnings.warn("Seed will be ignored if initial medoids are given")
		return medoids
```

However, the `warnings` module has not been imported yet. Therefore, I am getting the following error when calling `kmedoids`:
`NameError: name 'warnings' is not defined`.

**Comment by lale1009** [comment]
Hi,

I've added this change to another bug fix.

Fixed in https://github.com/kno10/python-kmedoids/commit/33dd58ce0427cc55342b6548334a566bf4ea0c83
